--- 

### 2020 FALL
### DSGA1007

--- 

### HW02
### Due Date: 2020-10-08, 5PM

Firstname: Emma

Lastname: Muhleman

E-mail: emm10005@nyu.edu


--- 

Enter your solutions below,  and submit this notebook

### Problem 01 (10 points):

1. 1 (5 points) Write a function that iteratively calculates factorial $n!$ of an integer $n \geq 0$, where $n!=1 \cdot 2 \cdot \dots \cdot n$. Evaluate the function for $n=10$.


1. 2 (5 points) Write a function that recursively calculates factorial $n!$ of an integer $n \geq 0$, where $n!=1 \cdot 2 \cdot \dots \cdot n$. Evaluate the function for $n=10$.


In [2]:
#1.1 

# Writes a function f_iter(n) that iteratively calculates the factorial n!
# Shows the output of the function where n = 10 of 10!

def f_iter(n):   
    if n <= 1:
        return 1
    else:
        p = 1
        for i in range(1, n + 1):
            p *= i        
        return p
f_iter(10)

3628800

In [3]:
# 1.2 

# Writes a function f(n) that recursively calculates factorial n! for any n: {0, 1, ...}
# compute f(10) to return the factorial of 10, or 10!

def f(n):
    p = 1
    if n <= 1:
        return 1
    else:
        return n * f(n - 1)
f(10)

3628800

### Problem 02 (50 points)

Let $M$ be a real quadratic matrix, that is, the number of rows and columns are the same. 

2.1 (20 points) Write a function that *recursively* calculates the power of matrix to the exponent $k$ (by the definition of the matrix multiplication). Here $k \geq 0$ is an integer.

```def matrix_mult_rec(M, k):
    return M_to_power
```    
    

2.2 (10 points) What is the number of calls, that is, how many times the function has been called for $k=100$?

2.3 (15 points) Given the same question as one in 2.2, what is the answer for a general input $k$?

2.4. (5 points) What is the answer for `M=np.ones((5, 5))` and `k=5`?

In [4]:
import numpy as np

In [5]:
M = np.array([[1, 2], [4, 5]])

In [6]:
# 2.1

def matrix_mult_rec(M, k):
    if k == 0:
        return np.identity(len(M))
    else:
        return M @ matrix_mult_rec(M,k-1)   

matrix_mult_rec(M, 2)

array([[ 9., 12.],
       [24., 33.]])

In [7]:
# 2.2 
# Add a global to record the call

count = 0
def matrix_mult_rec(M, k):
    global count
    count += 1
    import numpy as np
    if k == 0:
        return np.identity(len(M))
    else:
        return M @ matrix_mult_rec(M,k-1) 
    
matrix_mult_rec(M, k=100)
print('The function has been called for', count, 'times when k=%d' %100)

The function has been called for 101 times when k=100


In [8]:
# 2.3
# The function has been called for k+1 times for a general k

In [9]:
# 2.4
M = np.ones((5, 5))
k = 5

matrix_mult_rec(M, k)

array([[625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.],
       [625., 625., 625., 625., 625.]])

### Problem 03 (20 points):

3.1 (5 points) Write a function that performs a bubble sort. 

3.2 (5 points) Write a function that performs a merge sort. 

3.3 (5 points) Generate a random numpy array $a$, of length $n=10000$, where each component is a random number independently and uniformly generated from the interval $[0, 1]$. 

3.4 (5 points) Estimate the run-times and print the difference when applied the functions from 3.1 and 3.2 on the array $a$. To estimate the run-times you can use the following part: 

In [10]:
# 3.1 bubble sort
def bubble_sort(arr):
    for i in range(len(arr)-1): 
        for j in range(i+1,len(arr)):
            if arr[i]>arr[j]:
                arr[i],arr[j] = arr[j],arr[i]
                
arr = [3,4,5,9,6,7,8,4,2,2,2]
print(arr)
bubble_sort(arr)
print(arr)            

[3, 4, 5, 9, 6, 7, 8, 4, 2, 2, 2]
[2, 2, 2, 3, 4, 4, 5, 6, 7, 8, 9]


In [11]:
# 3.2 merge sort
def merge_two_list(arr_left,arr_right):
    
    #init values
    merged_list=[]
    num_left , num_right = 0,0
    
    while num_left < len(arr_left) and num_right < len(arr_right):
        
        if arr_left[num_left] <= arr_right[num_right]:
            merged_list.append(arr_left[num_left])
            num_left += 1
            
        else: 
            merged_list.append(arr_right[num_right])
            num_right += 1
            
    if num_left == len(arr_left):
        merged_list += arr_right[num_right:]
        
    else: merged_list += arr_left[num_left:]
        
    return merged_list

def merge_sort(arr):
    
    #define the end of recursive
    if len(arr)<=1:
        return arr
    
    middle = len(arr)//2
    arr_left = arr[:middle]
    arr_right = arr[middle:]
    
    return list(merge_two_list(merge_sort(arr_left), merge_sort(arr_right)))


arr=[3,2,1,5,6,8,9,4,2]
merge_sort(arr)

[1, 2, 2, 3, 4, 5, 6, 8, 9]

In [12]:
# 3.3
n = 10000
a = np.random.rand(n)
a

array([0.61966202, 0.5529275 , 0.2495616 , ..., 0.80424832, 0.14474722,
       0.31733479])

In [13]:
# 3.4
import datetime

start_time_bubble =  datetime.datetime.now()
bubble_sort(a)
end_time_bubble =  datetime.datetime.now()
run_time_bubble = end_time_bubble - start_time_bubble

start_time_merge =  datetime.datetime.now()
merge_sort(a)
end_time_merge =  datetime.datetime.now()
run_time_merge = end_time_merge - start_time_merge
print("The run-time for bubble sort is:",run_time_bubble,"\nThe run-time for merge sort is:",run_time_merge)

The run-time for bubble sort is: 0:00:21.246368 
The run-time for merge sort is: 0:00:00.036785



### Problem 04 (20 points)


The provided file 'nba2020.csv' contains the schedules and information of the NBA games for 2020. Using the unix commands, covered in Lecture04, write scripts which will display:
    
4.1 (5 points) a unique list of NBA teams, provided in the file;

4.2 (5 points) the number of those NBA teams;

4.3 (5 points) a unique list of the times -- provided in the file -- when the NBA matches were played;

4.4 (5 points) the number of these unique times.

**Important:** to skip the header of file you can use: 
    
`!tail -n+2 nba2020.csv`


Since,

``-n, --lines=[+]NUM       output the last NUM lines, instead of the last 10;
                             or use -n +NUM to output starting with line NUM``
        

In [14]:
#print a working directory i.e. print the current path 

%pwd

'/Users/emmamuhleman/Dropbox/notebooks/nb1007/__HOMEWORKS__/hwk2'

In [15]:
# 4.1 a unique list of NBA teams, provided in the file

!tail -n+2 nba2020.csv | cut -d "," -f 3 | sort | uniq


Atlanta Hawks
Boston Celtics
Brooklyn Nets
Charlotte Hornets
Chicago Bulls
Cleveland Cavaliers
Dallas Mavericks
Denver Nuggets
Detroit Pistons
Golden State Warriors
Houston Rockets
Indiana Pacers
Los Angeles Clippers
Los Angeles Lakers
Memphis Grizzlies
Miami Heat
Milwaukee Bucks
Minnesota Timberwolves
New Orleans Pelicans
New York Knicks
Oklahoma City Thunder
Orlando Magic
Philadelphia 76ers
Phoenix Suns
Portland Trail Blazers
Sacramento Kings
San Antonio Spurs
Toronto Raptors
Utah Jazz
Washington Wizards


In [16]:
# 4.2  

!tail -n+2 nba2020.csv | cut -d "," -f 3 | sort | uniq | wc -l

      30


In [17]:
# 4.3

!tail -n+2 nba2020.csv | cut -d "," -f 2 | sort | uniq


10:00p
10:30p
3:30p
5:00p
6:00p
7:00p
7:30p
8:00p
8:30p
9:00p
9:30p


In [18]:
# 4.4

!tail -n+2 nba2020.csv | cut -d "," -f 2 | sort | uniq | wc -l

      12
